" use spaces
set tabstop=4 shiftwidth=4 expandtab

set encoding=utf-8
set number

" don't split up
set splitbelow splitright 

" needed for rust.vim
syntax enable
filetype plugin indent on

" ------------------------- "
" Shortcuts
" ------------------------- "
set pastetoggle=<f2>

" ctrl + s for save. 
" Make sure to unbind from .bashrc too (zsh should be ok)
:nmap <c-s> :w<CR>
:imap <c-s> <Esc>:w<CR>a

"  switch panes with just ctrl + direction keys
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" ------------------------ "
" Plugins"
" ------------------------ "
" vimplug
" :PlugInstall :PlugUpgrade
" ------------------------ "
call plug#begin('~/.vim/plugged')

Plug 'rust-lang/rust.vim'
Plug 'scrooloose/syntastic'

Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

Plug 'jremmen/vim-ripgrep'

call plug#end()

"--------------------------"
"start rip-grep from root of a project"
"--------------------------"
if executable('rg')
    let g:rg_derive_root='true'
endif

"----------------------------"
" Rust
"----------------------------"
let g:rustfmt_autosave = 1

" recommended settings for syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_check_on_wq = 0
" let g:syntastic_auto_loc_list = 1
" let g:syntastic_check_on_open = 1

"----------------------------"
" Plugins Rust
"----------------------------"

" fzf shortcut - exclude files in gitignore
map <s-f> <Esc><ESc>:GFiles!<CR>

" Syntastic
nmap <F3> :Errors<CR>
"or SyntasticReset
nmap <F4> :lclose<CR> 